version: '3.3'

networks:
  proxy_traefik:
    external: true
  internal-network:

services:
  app:
    image: chromamaster/dokuwiki_arm32v7:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:wiki.dropi.com.es"
        - "traefik.port=80"
        - "traefik.docker.network=proxy_traefik"
    networks:
      - proxy_traefik
      - internal-network
    volumes:
      - ./data/app/data:/var/www/html/data
      - ./data/app/config:/var/www/html/conf
      - ./data/nginx.conf:/etc/nginx/nginx.conf
